name: Static Analysis

on: ['push', 'pull_request']

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dependency-version: [prefer-lowest, prefer-stable]

    name: PHPStan (${{ matrix.dependency-version }})

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-progress --ansi

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress --ansi

  infection:
    runs-on: ubuntu-latest

    name: Infection

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        tools: composer
        coverage: pcov

    - name: Install Dependencies
      run: composer update --no-interaction --prefer-dist --no-progress --ansi

    - name: Run Infection
      run: vendor/bin/infection --no-progress --ansi --min-msi=100 --min-covered-msi=100 --threads=4
